// End-to-end parity check against the Torch reference.
//
// The fixture is generated by `Scripts/generate_parity_fixture.py` running
// `Ruicheng/moge-2-vitl-normal` through `MoGeModel.infer` on a real image.
// We re-run the same input through the Swift pipeline and compare the final
// `infer` outputs (post LM solver, post projection) — no intermediate
// forward checks, since the heads aren't user-visible.
//
// Tolerances are loose on `points`/`depth`/`intrinsics` because the focal
// recovery uses two different LM solvers (scipy on the Python side,
// hand-rolled in Swift). The thresholds below are calibrated to pass on a
// correctly ported model and fail on real regressions (off-by-one resampling,
// wrong remap branch, swapped axes, etc.).

import Foundation
import MLX
import XCTest

@testable import MLXMoGe

final class ParityFixtureTests: XCTestCase {
    func testInferEndToEndMatchesTorchReference() throws {
        let env = ProcessInfo.processInfo.environment

        let packageRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let defaultFixtureDir = packageRoot.appendingPathComponent("Tests/Fixtures").path
        let fixtureDir = env["MOGE_FIXTURE_DIR"] ?? defaultFixtureDir
        let fixtureURL = URL(fileURLWithPath: fixtureDir)
            .appendingPathComponent("moge_infer.safetensors")

        guard let weightsPath = env["MOGE_WEIGHTS"] else {
            throw XCTSkip("Set MOGE_WEIGHTS to a converted weights directory (config.json + weights.safetensors).")
        }
        guard FileManager.default.fileExists(atPath: fixtureURL.path) else {
            throw XCTSkip("Parity fixture not found at \(fixtureURL.path). Generate with Scripts/generate_parity_fixture.py.")
        }
        guard FileManager.default.fileExists(atPath: weightsPath) else {
            throw XCTSkip("MOGE_WEIGHTS path does not exist: \(weightsPath)")
        }

        let fixture = try loadArrays(url: fixtureURL)
        guard let inputNHWC = fixture["input_nhwc"] else {
            XCTFail("Fixture missing input_nhwc")
            return
        }

        let pipeline = try MoGePipeline.fromPretrained(weightsPath, dtype: .float16)
        // Match the resolution_level used by the generator script.
        let outputs = pipeline.predict(
            inputNHWC,
            resolutionLevel: 5,
            forceProjection: true,
            applyMask: true
        )

        // Tolerances per output. `meanAtol` is the average absolute diff over
        // valid (non-NaN) elements; `atol` is the worst-case per-element bound.
        // Per-element `atol` is generous on `normal`/`depth`/`points` because
        // a few pixels at depth/orientation discontinuities flip sign or jump
        // after bilinear upsample under fp16 — a known mode that doesn't
        // indicate a port bug. `meanAtol` is what catches real regressions.
        try assertClose(outputs, fixture, key: "mask",       atol: 0.05, meanAtol: 5e-3)
        try assertClose(outputs, fixture, key: "normal",     atol: 1.0,  meanAtol: 2e-2)
        try assertClose(outputs, fixture, key: "depth",      atol: 1.0,  meanAtol: 2e-2)
        try assertClose(outputs, fixture, key: "points",     atol: 1.0,  meanAtol: 2e-2)
        try assertClose(outputs, fixture, key: "intrinsics", atol: 5e-3, meanAtol: 5e-4)
    }

    private func assertClose(
        _ actualOutputs: [String: MLXArray],
        _ fixture: [String: MLXArray],
        key: String,
        atol: Float,
        meanAtol: Float,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        guard let actual = actualOutputs[key] else {
            XCTFail("Missing Swift output '\(key)'", file: file, line: line)
            return
        }
        guard let expected = fixture["output.\(key)"] else {
            XCTFail("Missing fixture output.\(key)", file: file, line: line)
            return
        }

        let actualF = actual.asType(.float32)
        let expectedF = expected.asType(.float32)
        eval(actualF, expectedF)

        XCTAssertEqual(
            actualF.shape, expectedF.shape,
            "shape mismatch for \(key): swift=\(actualF.shape) torch=\(expectedF.shape)",
            file: file, line: line
        )
        guard actualF.shape == expectedF.shape else { return }

        let a: [Float] = actualF.asArray(Float.self)
        let e: [Float] = expectedF.asArray(Float.self)

        var maxAbs: Float = 0
        var sumAbs: Double = 0
        var validCount = 0
        for (av, ev) in zip(a, e) {
            // NaN slots come from `apply_mask=true` (invalid regions). Either
            // both sides should be NaN, or neither should — but we don't
            // enforce mask-set equality strictly; we just skip pairs where
            // either is NaN/inf and let the `mask` test catch shape changes.
            guard av.isFinite, ev.isFinite else { continue }
            let d = abs(av - ev)
            if d > maxAbs { maxAbs = d }
            sumAbs += Double(d)
            validCount += 1
        }
        XCTAssertGreaterThan(validCount, 0, "no finite values to compare for '\(key)'", file: file, line: line)
        let meanAbs = validCount > 0 ? Float(sumAbs / Double(validCount)) : .infinity

        if maxAbs > atol || meanAbs > meanAtol {
            XCTFail(
                "\(key) parity failed: maxAbs=\(maxAbs) (limit \(atol)), meanAbs=\(meanAbs) (limit \(meanAtol)), n=\(validCount)",
                file: file, line: line
            )
        } else {
            print("[parity] \(key): maxAbs=\(maxAbs), meanAbs=\(meanAbs), n=\(validCount)")
        }
    }
}
